services:
  postgres:
    image: postgres:alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    networks:
      - app
    env_file:
      - .env.local
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db_seed.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}" ]
      interval: 5s
      start_period: 1s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go-app
    restart: always
    networks:
      - app
    env_file:
      - .env.local
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: ["go", "run", "cmd/app/main.go"]
    
volumes:
  postgres-db:

networks:
  app: